"""Tests for GET /api/services/reliability and the nightly snapshot job.

Session 25, Tier 1.  The scorer's arithmetic lives in
``test_reliability.py``; this file covers the adapter — which services
get scored, how the muted set is assembled, and the wire shape.
"""

from datetime import UTC, datetime, timedelta
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from sysadmin.core.contracts import ReliabilityResponse
from sysadmin.monitor.reliability import score_service
from sysadmin.monitor.reliability_history import (
    compute_reliability,
    muted_service_names,
    record_reliability_snapshot,
)
from sysadmin.monitor.routers.services import summarise, to_contract
from sysadmin.monitor.services import get_services
from tests.conftest import set_services

NOW = datetime(2026, 8, 7, 12, 0, tzinfo=UTC)
INTERVAL = 60  # mock_config's health_check_interval_seconds


@pytest.fixture(autouse=True)
def _pinned_route_clock():
    """Pin the route's clock to ``NOW``, the one every fixture is built from.

    The endpoint is computed live by design, so it reads ``datetime.now``
    rather than taking a ``now`` argument the way ``compute_reliability``
    does.  That left this file with **two clocks**: the scorer calls pinned
    to ``NOW`` and the nine endpoint calls following the wall clock, with
    the fixture rows anchored to ``NOW`` in both cases.  As real time drew
    away from ``NOW`` the rows slid out of the seven-day window, and the
    tests began to fail on a date rather than on a change.

    ``test_endpoint_filters_by_confidence`` went first, on 2026-08-11, at
    the 3.5-day mark where a seven-day run of checks stops covering half
    the window and ``_confidence`` correctly downgrades it.  The remaining
    eight had until 2026-08-14, when the run would have left the window
    outright.  One clock, and none of that is reachable.
    """
    with patch("sysadmin.monitor.routers.services.datetime") as clock:
        clock.now.return_value = NOW
        yield


def _rows(mock_session, rows):
    """Make ``session.execute`` yield ``(service_name, status, checked_at)``."""
    result = MagicMock()
    result.all.return_value = rows
    mock_session.execute = AsyncMock(return_value=result)


def _checks(name: str, statuses: list[str], *, end: datetime = NOW) -> list[tuple]:
    return [
        (name, status, end - timedelta(seconds=INTERVAL * (len(statuses) - 1 - i)))
        for i, status in enumerate(statuses)
    ]


# ── which services get scored ────────────────────────────────────────


async def test_every_configured_service_is_scored_even_with_no_checks(
    mock_config, mock_session
):
    """A configured service the monitor has never reached is a finding,
    not an absence — live examples venture-chat and pgbackrest-backup-timer,
    both added to config.yaml before the backend restarted."""
    _rows(mock_session, _checks("test-api", ["ok"] * 100))

    scores = await compute_reliability(mock_session, mock_config, now=NOW)

    assert {s.service for s in scores} == {
        s.name for s in get_services().services
    }
    unchecked = next(s for s in scores if s.service == "test-tcp")
    assert unchecked.checks_recorded == 0
    assert unchecked.confidence == "low"
    assert unchecked.confidence_reason == "no checks recorded in the window"


async def test_retired_services_in_the_table_are_not_scored(
    mock_config, mock_session
):
    """ollama and personal-assistant still have rows from before they were
    retired on 2026-07-24. Scoring them would publish verdicts on services
    that no longer exist."""
    _rows(mock_session, _checks("ollama", ["critical"] * 100))

    scores = await compute_reliability(mock_session, mock_config, now=NOW)

    assert "ollama" not in {s.service for s in scores}


async def test_no_configured_services_yields_no_scores(mock_config, mock_session):
    set_services()
    scores = await compute_reliability(mock_session, mock_config, now=NOW)
    assert scores == []
    mock_session.execute.assert_not_called()


async def test_the_configured_window_and_interval_are_used(
    mock_config, mock_session
):
    mock_config.agents.sysadmin.reliability.window_days = 3
    _rows(mock_session, [])

    scores = await compute_reliability(mock_session, mock_config, now=NOW)

    assert all(s.window_days == 3 for s in scores)
    assert all(s.checks_expected == 3 * 86400 // INTERVAL for s in scores)


# ── the muted set ────────────────────────────────────────────────────


def test_muted_set_reads_the_service_flag(mock_config):
    get_services().services[0].mute = True
    assert "test-api" in muted_service_names(mock_config)


def test_muted_set_reads_the_tray_list_too(mock_config):
    """projects.yaml services are generated by to_monitored_services and
    have no mute flag, so notifications.tray.mute_services is the only
    way to declare one expected-down."""
    mock_config.notifications.tray.mute_services = ["alfred-frontend"]
    assert "alfred-frontend" in muted_service_names(mock_config)


def test_muted_set_is_the_union_without_duplication(mock_config):
    get_services().services[0].mute = True
    mock_config.notifications.tray.mute_services = ["test-api", "other"]
    assert muted_service_names(mock_config) == {"test-api", "other"}


async def test_a_muted_service_is_scored_with_waived_deductions(
    mock_config, mock_session
):
    get_services().services[0].mute = True
    _rows(mock_session, _checks("test-api", ["critical"] * 100))

    scores = await compute_reliability(mock_session, mock_config, now=NOW)
    muted = next(s for s in scores if s.service == "test-api")

    assert muted.score == 100
    assert muted.muted is True
    assert muted.waived_points > 0
    assert all(d.waived for d in muted.deductions)


# ── the endpoint ─────────────────────────────────────────────────────


async def test_endpoint_returns_every_service_worst_first(
    test_client, mock_session
):
    _rows(mock_session, _checks("test-api", ["ok"] * 50 + ["critical"] * 50))

    body = (await test_client.get("/api/services/reliability")).json()

    assert body["count"] == 4
    assert body["services"][0]["service"] == "test-api"
    assert body["services"][0]["score"] < 100
    assert body["window_days"] == 7
    assert body["computed_at"] is not None


async def test_endpoint_reports_attributable_deductions(test_client, mock_session):
    _rows(mock_session, _checks("test-api", ["ok"] * 50 + ["critical"] * 50))

    body = (await test_client.get("/api/services/reliability")).json()
    worst = body["services"][0]

    assert {d["kind"] for d in worst["deductions"]} == {"downtime", "instability"}
    assert worst["score"] == 100 - sum(d["points"] for d in worst["deductions"])


async def test_endpoint_summary_counts_grades(test_client, mock_session):
    _rows(mock_session, _checks("test-api", ["critical"] * 100))

    summary = (await test_client.get("/api/services/reliability")).json()["summary"]

    assert summary["services_scored"] == 4
    assert summary["failing"] == 1
    assert summary["reliable"] == 3
    # 3 unchecked services + nothing else measured
    assert summary["low_confidence"] == 4


async def test_endpoint_summary_ignores_the_filter(test_client, mock_session):
    """A filtered page whose totals moved with the filter would make
    '3 unreliable' mean something different on every request."""
    _rows(mock_session, _checks("test-api", ["critical"] * 100))

    body = (await test_client.get(
        "/api/services/reliability?grade=failing"
    )).json()

    assert body["count"] == 1
    assert body["summary"]["services_scored"] == 4


async def test_endpoint_filters_by_grade(test_client, mock_session):
    _rows(mock_session, _checks("test-api", ["critical"] * 100))

    body = (await test_client.get(
        "/api/services/reliability?grade=reliable"
    )).json()

    assert body["count"] == 3
    assert all(s["grade"] == "reliable" for s in body["services"])


async def test_endpoint_filters_by_confidence(test_client, mock_session):
    _rows(mock_session, _checks("test-api", ["ok"] * (7 * 1440)))

    body = (await test_client.get(
        "/api/services/reliability?confidence=high"
    )).json()

    assert body["count"] == 1
    assert body["services"][0]["service"] == "test-api"


@pytest.mark.parametrize(
    "query",
    ["grade=nope", "confidence=maybe"],
)
async def test_endpoint_rejects_unknown_filter_values(
    test_client, mock_session, query
):
    _rows(mock_session, [])
    assert (
        await test_client.get(f"/api/services/reliability?{query}")
    ).status_code == 400


async def test_endpoint_never_404s_before_the_first_nightly_job(
    test_client, mock_session
):
    """Unlike /api/units/status, this recomputes live — there is no
    stored row to be missing."""
    _rows(mock_session, [])

    response = await test_client.get("/api/services/reliability")

    assert response.status_code == 200
    assert response.json()["count"] == 4


async def test_endpoint_response_parses_as_its_contract(test_client, mock_session):
    _rows(mock_session, _checks("test-api", ["ok"] * 50 + ["critical"] * 50))

    payload = (await test_client.get("/api/services/reliability")).json()
    parsed = ReliabilityResponse.from_dict(payload)

    assert parsed.count == 4
    assert parsed.services[0].deductions[0].points > 0
    assert parsed.summary.services_scored == 4


# ── the nightly snapshot job ─────────────────────────────────────────


async def test_snapshot_job_writes_one_row_per_service(mock_config, mock_session):
    _rows(mock_session, _checks("test-api", ["ok"] * 100))

    ctx = MagicMock()
    ctx.__aenter__ = AsyncMock(return_value=mock_session)
    ctx.__aexit__ = AsyncMock(return_value=False)

    with patch(
        "sysadmin.monitor.reliability_history.get_config", return_value=mock_config
    ), patch(
        "sysadmin.monitor.reliability_history.get_scheduler_session",
        return_value=ctx,
    ):
        written = await record_reliability_snapshot()

    assert written == 4
    assert mock_session.add.call_count == 4
    row = mock_session.add.call_args_list[0].args[0]
    assert row.service_name
    assert 0 <= row.score <= 100
    assert isinstance(row.deductions, list)


async def test_snapshot_job_is_a_noop_when_disabled(mock_config):
    mock_config.agents.sysadmin.reliability.enabled = False

    with patch(
        "sysadmin.monitor.reliability_history.get_config", return_value=mock_config
    ):
        assert await record_reliability_snapshot() == 0


# ── presentation helpers ─────────────────────────────────────────────


def test_summarise_over_an_empty_list_does_not_divide_by_zero():
    summary = summarise([])
    assert summary.services_scored == 0
    assert summary.mean_score == 100.0


def test_to_contract_carries_the_deductions_through():
    score = score_service(
        "svc",
        [],
        now=NOW,
    )
    info = to_contract(score)
    assert info.service == "svc"
    assert info.deductions == []
    assert info.window_start is not None
