"""Tests for the roadmap document reader.

The parsing rules here were derived from two real handoffs that disagree
about everything except being markdown: the one the SessionEnd hook
generates (``## Next action``, machine written) and SportsAnalyser's
hand-authored one (``## Next Planned Sessions``, prose, five months old).
Both shapes are pinned below — a parser that only handles the generated
form would report "no next action" for every hand-written handoff on the
box, silently.
"""

from datetime import UTC, datetime

import pytest

from sysadmin.services.roadmap import (
    count_checked,
    count_open_snags,
    count_unchecked,
    first_unchecked_task,
    handoff_date,
    is_placeholder,
    next_action_from_handoff,
    scan_roadmap,
)

GENERATED_HANDOFF = """# Handoff — 2026-08-06

_Generated by the SessionEnd hook._

**Branch:** `main`

## Next action

Session 28: Roadmap findings → Parse tasks.md

## Uncommitted at session end

    M config.yaml
"""

HANDWRITTEN_HANDOFF = """# Session Handoff — 2026-03-07

## What Was Done

Added squad availability as ML features.

## Current State

Everything green.

## Next Planned Sessions

- Session 17: Odds movement features
- Session 18: Live scores
"""

TASKS = """# Tasks

## Session 24: File organiser tiers

- [x] Tier 1 done
- [ ] Fix the 150-word limit

## Session 25: Service reliability

- [ ] Score services from health_checks
"""

SNAGS = """# Snag List

## Open Issues

- [P2] SNAG-AGENT-002: Log aggregator raises one alert per error line (2026-07-24)
- [P3] SNAG-API-009: Something else (2026-08-01)

## Fixed Issues

| SNAG | Title | Fixed |
|------|-------|-------|
| SNAG-CONF-001 | Wrong-case path | 2026-08-04 |
| SNAG-SYSD-001 | Missing XDG_RUNTIME_DIR | 2026-07-24 |
"""


class TestNextAction:
    def test_generated_handoff_uses_next_action_heading(self):
        assert next_action_from_handoff(GENERATED_HANDOFF) == (
            "Session 28: Roadmap findings → Parse tasks.md"
        )

    def test_handwritten_handoff_matches_next_substring(self):
        """"Next Planned Sessions" must match — heading text is not fixed."""
        assert next_action_from_handoff(HANDWRITTEN_HANDOFF) == (
            "Session 17: Odds movement features"
        )

    def test_falls_back_to_unchecked_box(self):
        text = "# Handoff — 2026-08-06\n\n## Status\n\n- [ ] Ship the thing\n"
        assert next_action_from_handoff(text) == "Status → Ship the thing"

    def test_opening_prose_is_never_guessed_at(self):
        """A handoff's first paragraph is what was *finished*, not what's next."""
        text = "# Handoff — 2026-08-06\n\n## What Was Done\n\nFinished the parser.\n"
        assert next_action_from_handoff(text) is None

    def test_empty_next_section_does_not_win(self):
        text = (
            "# Handoff\n\n## Next steps\n\n\n## Also\n\n- [ ] Real item\n"
        )
        assert next_action_from_handoff(text) == "Also → Real item"


class TestTasks:
    def test_first_unchecked_carries_its_heading(self):
        assert first_unchecked_task(TASKS) == (
            "Session 24: File organiser tiers → Fix the 150-word limit"
        )

    def test_checked_boxes_are_skipped(self):
        assert "Tier 1 done" not in (first_unchecked_task(TASKS) or "")

    def test_counts(self):
        assert count_unchecked(TASKS) == 2
        assert count_checked(TASKS) == 1

    def test_no_boxes_at_all(self):
        assert first_unchecked_task("# Tasks\n\nProse only.\n") is None
        assert count_unchecked("") == 0

    def test_asterisk_bullets_count(self):
        assert count_unchecked("* [ ] one\n* [x] two\n") == 1


class TestSnags:
    def test_only_open_section_counted(self):
        """The fixed-snag table must not inflate the open count."""
        assert count_open_snags(SNAGS) == 2

    def test_no_open_section(self):
        assert count_open_snags("# Snags\n\n## Fixed Issues\n\n| a | b |\n") == 0


class TestHandoffDate:
    def test_reads_iso_date_from_first_heading(self):
        assert handoff_date(GENERATED_HANDOFF).isoformat() == "2026-08-06"
        assert handoff_date(HANDWRITTEN_HANDOFF).isoformat() == "2026-03-07"

    def test_falls_back_when_heading_has_no_date(self):
        from datetime import date

        fb = date(2020, 1, 1)
        assert handoff_date("# Handoff\n\ntext\n", fallback=fb) == fb

    def test_impossible_date_returns_fallback_not_crash(self):
        from datetime import date

        fb = date(2020, 1, 1)
        assert handoff_date("# Handoff — 2026-13-45\n", fallback=fb) == fb


class TestScanRoadmap:
    @pytest.fixture
    def project(self, tmp_path):
        (tmp_path / "docs" / "sessions").mkdir(parents=True)
        (tmp_path / "docs" / "roadmap").mkdir(parents=True)
        return tmp_path

    def test_empty_project_reports_everything_missing(self, tmp_path):
        info = scan_roadmap(tmp_path)
        assert info["has_handoff"] is False
        assert info["next_action"] is None
        assert info["next_action_source"] is None
        assert set(info["missing_docs"]) == {"handoff", "tasks", "status"}

    def test_handoff_wins_over_tasks(self, project):
        (project / "docs/sessions/handoff.md").write_text(GENERATED_HANDOFF)
        (project / "docs/roadmap/tasks.md").write_text(TASKS)

        info = scan_roadmap(project)
        assert info["next_action_source"] == "handoff"
        assert "Session 28" in info["next_action"]
        # tasks are still counted even when they lose the next-action race
        assert info["open_tasks"] == 2

    def test_checkbox_free_task_list_reports_unknown_not_zero(self, project):
        """Alfred tracks sessions in a status table — 0 would be a lie."""
        (project / "docs/roadmap/tasks.md").write_text(
            "# Tasks\n\n| Session | Status |\n|---|---|\n| A | Planned |\n"
        )
        info = scan_roadmap(project)
        assert info["open_tasks"] is None
        assert info["done_tasks"] is None

    def test_all_tasks_done_reports_zero_not_unknown(self, project):
        (project / "docs/roadmap/tasks.md").write_text("- [x] done\n- [x] also\n")
        info = scan_roadmap(project)
        assert info["open_tasks"] == 0
        assert info["done_tasks"] == 2

    def test_handoff_found_in_docs_roadmap_too(self, project):
        """Alfred's convention — same document, different directory."""
        (project / "docs/roadmap/handoff.md").write_text(GENERATED_HANDOFF)
        info = scan_roadmap(project)
        assert info["has_handoff"] is True
        assert info["next_action_source"] == "handoff"

    def test_tasks_used_when_no_handoff(self, project):
        (project / "docs/roadmap/tasks.md").write_text(TASKS)

        info = scan_roadmap(project)
        assert info["next_action_source"] == "tasks"
        assert "docs/roadmap/tasks.md" in info["next_action"]

    def test_handoff_without_a_next_action_defers_to_tasks(self, project):
        (project / "docs/sessions/handoff.md").write_text(
            "# Handoff — 2026-08-06\n\n## What Was Done\n\nStuff.\n"
        )
        (project / "docs/roadmap/tasks.md").write_text(TASKS)

        info = scan_roadmap(project)
        assert info["next_action_source"] == "tasks"
        # the handoff still contributes its age
        assert info["handoff_age_days"] is not None

    def test_handoff_age_measured_from_authored_date(self, project):
        """Not from mtime — a fresh clone rewrites every mtime on disk."""
        (project / "docs/sessions/handoff.md").write_text(HANDWRITTEN_HANDOFF)

        now = datetime(2026, 3, 27, tzinfo=UTC)
        info = scan_roadmap(project, now=now)
        assert info["handoff_age_days"] == 20

    def test_snags_counted(self, project):
        (project / "docs/roadmap/snag_list.md").write_text(SNAGS)
        assert scan_roadmap(project)["open_snags"] == 2

    def test_root_level_tasks_md_accepted(self, tmp_path):
        (tmp_path / "TASKS.md").write_text(TASKS)
        info = scan_roadmap(tmp_path)
        assert info["next_action_source"] == "tasks"
        assert "TASKS.md" in info["next_action"]

    def test_unreadable_file_is_treated_as_absent(self, project):
        """A permissions error on one project must not abort a scan."""
        bad = project / "docs/roadmap/tasks.md"
        bad.write_text(TASKS)
        bad.chmod(0o000)
        try:
            info = scan_roadmap(project)
            # Either unreadable (absent) or readable as root — both fine,
            # the point is that it does not raise.
            assert info["next_action_source"] in (None, "tasks")
        finally:
            bad.chmod(0o644)


class TestPlaceholderRejection:
    """Template scaffolds must not be published as a project's next action.

    Found by the 2026-08-06 estate init: several repos were created from a
    doc template and never filled in, so their task lists are
    syntactically perfect and semantically empty. InvestingAssistant's
    board entry read "_Task 1_".
    """

    TEMPLATE = """# Tasks & Sessions

## Active Sessions

### Session 1: _Description_

- [ ] _Task 1_
- [ ] _Task 2_
"""

    def test_all_placeholder_list_yields_nothing(self):
        assert first_unchecked_task(self.TEMPLATE) is None

    def test_real_item_after_placeholders_wins(self):
        text = self.TEMPLATE + "\n## Real\n\n- [ ] Restore the webcam capture path\n"
        assert first_unchecked_task(text) == "Real → Restore the webcam capture path"

    def test_placeholder_heading_is_dropped_not_the_item(self):
        text = "### Session 1: _Description_\n\n- [ ] Fix the parser\n"
        assert first_unchecked_task(text) == "Fix the parser"

    @pytest.mark.parametrize("line", [
        "_Task 1_", "_Description_", "TODO", "TBD", "Task 2", "Item 3",
        "TODO: add first task", "***", "   ",
    ])
    def test_recognised_placeholders(self, line):
        assert is_placeholder(line) is True

    @pytest.mark.parametrize("line", [
        "Restore the webcam capture path",
        "Triage: decide whether to resume or archive this project",
        "M5-T05 — free-aim feel with the chase camera",
        "Add a git remote",
        "Fix the 150-word limit in the review prompt",
    ])
    def test_real_work_is_not_mistaken_for_a_placeholder(self, line):
        """False positives silently hide real work — bias against them."""
        assert is_placeholder(line) is False

    def test_scan_falls_through_to_git_when_only_placeholders(self, tmp_path):
        (tmp_path / "docs" / "roadmap").mkdir(parents=True)
        (tmp_path / "docs/roadmap/tasks.md").write_text(self.TEMPLATE)
        info = scan_roadmap(tmp_path)
        assert info["next_action"] is None
        assert info["next_action_source"] is None
        # still counted — the boxes exist, they just say nothing
        assert info["open_tasks"] == 2
