"""Database-facing half of service reliability scoring (Session 25).

``sysadmin.monitor.reliability`` is pure — it scores a list of health
points and knows nothing about SQLAlchemy or config.  This module is the
adapter: it decides *which* services to score, pulls their checks, and
persists a daily snapshot.

The split matters because the formula is shared.  Both the live endpoint
and the nightly job call :func:`compute_reliability`, so the number a
consumer reads and the number the history records can never disagree
about how a score was arrived at.
"""

import logging
from dataclasses import asdict
from datetime import UTC, datetime, timedelta

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from sysadmin.core.config import AppConfig, get_config
from sysadmin.core.database import get_scheduler_session
from sysadmin.monitor.models.reliability_score import ReliabilityScore as ReliabilityScoreRow
from sysadmin.monitor.models.service_health import ServiceHealth
from sysadmin.monitor.reliability import (
    HealthPoint,
    ReliabilityScore,
    score_services,
)

logger = logging.getLogger(__name__)


def muted_service_names(config: AppConfig) -> set[str]:
    """Services declared expected-down, from either of the two places.

    ``mute: true`` on the monitored service and the tray's
    ``notifications.tray.mute_services`` list are the same declaration in
    two syntaxes, so the union is what "expected down" means.  Reading
    only the flag would be wrong in a way that is easy to miss: services
    contributed by projects.yaml are generated by
    ``ManagedProject.to_monitored_services`` and have no ``mute`` field
    at all, so the list is the *only* way to declare one of them.
    """
    muted = {s.name for s in config.agents.sysadmin.services if s.mute}
    muted |= set(config.notifications.tray.mute_services)
    return muted


async def compute_reliability(
    session: AsyncSession,
    config: AppConfig,
    *,
    now: datetime | None = None,
) -> list[ReliabilityScore]:
    """Score every configured service over the configured window.

    The population is **the configured services**, not the distinct
    names in ``service_health``.  Those differ in both directions and
    both differences matter: retired services (``ollama``,
    ``personal-assistant``) still have rows here and must not be scored,
    and a service just added to config.yaml has no rows at all — which is
    a finding, not an absence, so it is seeded with an empty series
    rather than skipped.
    """
    settings = config.agents.sysadmin.reliability
    now = now or datetime.now(UTC)
    window_start = now - timedelta(days=settings.window_days)

    names = [s.name for s in config.agents.sysadmin.services]
    if not names:
        return []

    series: dict[str, list[HealthPoint]] = {name: [] for name in names}

    rows = (
        await session.execute(
            select(
                ServiceHealth.service_name,
                ServiceHealth.status,
                ServiceHealth.checked_at,
            )
            .where(ServiceHealth.checked_at >= window_start)
            .where(ServiceHealth.service_name.in_(names))
        )
    ).all()

    for service_name, status, checked_at in rows:
        # The IN filter should make this total, but a row for a service
        # no longer configured is dropped rather than raising: retired
        # services (ollama, personal-assistant) keep rows here for 30
        # days after they stop being monitored, and a scoring job is not
        # the place to discover that a config entry went away.
        if service_name in series:
            series[service_name].append(
                HealthPoint(checked_at=checked_at, status=status)
            )

    bands = settings.grade_bands
    return score_services(
        series,
        muted=muted_service_names(config),
        window_days=settings.window_days,
        check_interval_seconds=config.agents.sysadmin.health_check_interval_seconds,
        now=now,
        grade_bands=(bands.reliable_min, bands.degraded_min, bands.unreliable_min),
    )


async def record_reliability_snapshot() -> int:
    """Persist today's score for every configured service. Cron entry point.

    Nothing reads these rows to answer a request —
    ``GET /api/services/reliability`` recomputes live — so this table is
    history for trending, and a failed run costs a data point rather than
    an outage.

    Returns the number of rows written.
    """
    config = get_config()
    if not config.agents.sysadmin.reliability.enabled:
        return 0

    now = datetime.now(UTC)
    async with get_scheduler_session() as session:
        scores = await compute_reliability(session, config, now=now)
        for score in scores:
            session.add(ReliabilityScoreRow(
                service_name=score.service,
                score=score.score,
                grade=score.grade,
                uptime_percent=score.uptime_percent,
                checks_recorded=score.checks_recorded,
                checks_measured=score.checks_measured,
                failed_checks=score.failed_checks,
                error_checks=score.error_checks,
                outage_episodes=score.outage_episodes,
                longest_outage_minutes=score.longest_outage_minutes,
                mean_hours_between_incidents=score.mean_hours_between_incidents,
                checks_expected=score.checks_expected,
                coverage_percent=score.coverage_percent,
                observed_days=score.observed_days,
                confidence=score.confidence,
                confidence_reason=score.confidence_reason,
                window_days=score.window_days,
                window_start=score.window_start,
                muted=score.muted,
                waived_points=score.waived_points,
                deductions=[asdict(d) for d in score.deductions],
                computed_at=now,
            ))

    logger.info(
        "reliability_snapshot_recorded",
        extra={
            "services": len(scores),
            "worst": scores[0].service if scores else None,
            "worst_score": scores[0].score if scores else None,
        },
    )
    return len(scores)
