"""Read a project's roadmap documents — the "where was I" layer.

The scanner has always answered "how tidy is this directory".  It has
never answered "what was I doing and what comes next", because the only
document it looked at was ``README.md`` and it only checked that the file
existed.  This module reads the four documents this estate actually keeps
— ``HANDOFF.md``, ``docs/roadmap/tasks.md``,
``snag_list.md`` and ``ideas.md`` — and extracts the one thing worth
surfacing per project: **the next action**.

Why handoff wins over tasks
---------------------------
``tasks.md`` records what was *planned*, decided when there was full
context.  ``handoff.md`` records where work *actually stopped*.  They
disagree, and when they do the record beats the plan — so handoff is
consulted first and ``tasks.md`` is the fallback.

The corollary is that **age qualifies the content**.  A next action from a
five-month-old handoff is not today's task, it is evidence the project
stalled; the caller gets ``handoff_age_days`` and decides how to present
it.  This module never editorialises — it reports.

Parsing is deliberately forgiving.  Handoffs on this box come in two
shapes: generated by the SessionEnd hook (``## Next action``, machine
written) and hand-authored (``## Next Planned Sessions``, prose).  Both
must work, so heading matching is a case-insensitive substring on
"next" rather than an exact string, and every extractor degrades to
``None`` instead of raising.

Pure module: no DB, no FastAPI, no git.  Give it a path, get a dict.
"""

from __future__ import annotations

import re
from datetime import UTC, date, datetime
from pathlib import Path
from typing import Any

# Where each document is looked for, in preference order.  The estate has
# settled on docs/roadmap/, but a root-level TASKS.md is the other shape
# seen in the wild and costs nothing to accept.
# Four handoff shapes exist on this box, and the canonical one is the root
# HANDOFF.md the Stop hook now requires (~/.claude/hooks/require-handoff.sh,
# 2026-08-10).  The other three are pre-existing and stay readable: repos
# migrate over weeks, and during that time most carry two.
#
# Order here is preference on a *tie only* — see _read_handoff.  It is
# deliberately not the selection rule.  SNAG-ROADMAP-003: when tuple order
# decided, venture-assistant's 6 KB root handoff and ImbaBots' 141 KB
# docs/handoff.md were invisible while an 850-byte generated stub beside
# each of them supplied the estate board's next action.
HANDOFF_PATHS = (
    "HANDOFF.md",
    "docs/sessions/handoff.md",
    "docs/handoff.md",
    "docs/roadmap/handoff.md",
)
TASKS_PATHS = ("docs/roadmap/tasks.md", "TASKS.md", "docs/TASKS.md")
SNAGS_PATHS = ("docs/roadmap/snag_list.md", "docs/roadmap/snags.md")
IDEAS_PATHS = ("docs/roadmap/ideas.md",)
STATUS_PATHS = ("docs/roadmap/STATUS.md", "STATUS.md")

_HEADING_RE = re.compile(r"^(#{1,6})\s+(.*?)\s*#*$")
_UNCHECKED_RE = re.compile(r"^\s*[-*]\s+\[ \]\s+(.*)$")
_CHECKED_RE = re.compile(r"^\s*[-*]\s+\[[xX]\]\s+")
_ISO_DATE_RE = re.compile(r"(\d{4})-(\d{2})-(\d{2})")

# A snag line looks like "- [P2] SNAG-AGENT-002: title (2026-07-24)".
# Fixed snags live in a markdown table below an "## Open Issues" section,
# so counting bare "SNAG-" occurrences would count the fixed ones too.
_SNAG_LINE_RE = re.compile(r"^\s*[-*]\s+.*\bSNAG-[A-Z]+-\d+", re.IGNORECASE)


def _read(project_path: Path, candidates: tuple[str, ...]) -> tuple[str | None, str]:
    """Return ``(text, relative_path)`` for the first candidate that reads.

    Unreadable is treated as absent: a roadmap document is advisory, and a
    permissions error on one project must not abort a portfolio scan.
    """
    for rel in candidates:
        f = project_path / rel
        try:
            if f.is_file():
                return f.read_text(encoding="utf-8", errors="replace"), rel
        except OSError:
            continue
    return None, ""


def _read_handoff(project_path: Path) -> tuple[str | None, str, list[str]]:
    """The most recently *authored* handoff, plus the also-rans it beat.

    Selection is by ``handoff_date`` — the date in the document's own first
    heading, falling back to mtime when it carries none — which is the same
    resolution ``scan_roadmap`` already uses to age a handoff.  Authored
    date beats mtime for the reason that function records: a clone or a
    checkout rewrites every mtime on disk, which would make a five-month-old
    handoff look like this morning's and silently outrank a current one.

    The fallback must apply *uniformly*.  Ranking every undated document
    below every dated one instead re-creates the bug from the other side:
    ImbaBots' 141 KB ``docs/handoff.md`` heads itself "Handoff — M5 (Tier
    2)" with no ISO date, and lost to an 882-byte generated stub written an
    hour earlier purely for carrying one.

    Tuple order breaks ties and nothing else.  It used to *be* the rule,
    and the rule was wrong in two of the three repos that had a choice — a
    generated stub outranking the real record purely by sitting earlier in
    a tuple (SNAG-ROADMAP-003).

    The losers are returned rather than discarded.  A repo holding two
    handoffs is a housekeeping finding worth surfacing; silently picking
    one is how the estate ended up with four conventions and nobody
    noticing.
    """
    found: list[tuple[tuple[date, float, int], str, str]] = []
    for idx, rel in enumerate(HANDOFF_PATHS):
        f = project_path / rel
        try:
            if not f.is_file():
                continue
            text = f.read_text(encoding="utf-8", errors="replace")
            mtime = f.stat().st_mtime
        except OSError:
            continue
        mtime_date = datetime.fromtimestamp(mtime, tz=UTC).date()
        written = handoff_date(text, fallback=mtime_date) or date.min
        # -idx so that a lower index wins a tie under a descending sort.
        found.append(((written, mtime, -idx), rel, text))

    if not found:
        return None, "", []

    found.sort(key=lambda item: item[0], reverse=True)
    _, best_rel, best_text = found[0]
    return best_text, best_rel, [rel for _, rel, _ in found[1:]]


def _sections(text: str) -> list[tuple[str, list[str]]]:
    """Split markdown into ``(heading, body_lines)`` pairs.

    Content before the first heading is returned under an empty heading so
    a document with no headings at all still yields its body.
    """
    out: list[tuple[str, list[str]]] = []
    heading = ""
    body: list[str] = []
    for line in text.splitlines():
        m = _HEADING_RE.match(line)
        if m:
            out.append((heading, body))
            heading = m.group(2)
            body = []
        else:
            body.append(line)
    out.append((heading, body))
    return out


def _first_meaningful(lines: list[str]) -> str | None:
    """First line carrying content — skipping blanks, quotes and list marks."""
    for raw in lines:
        line = raw.strip()
        if not line or line.startswith((">", "|", "---", "```")):
            continue
        line = _UNCHECKED_RE.sub(r"\1", line)
        line = re.sub(r"^\s*[-*]\s+", "", line)
        line = re.sub(r"^_+|_+$", "", line).strip()
        if line:
            return line
    return None


# Unedited template scaffolds. Several projects on this box were created
# from a doc template and never filled in, so their task lists are
# syntactically perfect and semantically empty: "- [ ] _Task 1_" under
# "### Session 1: _Description_". Those pass every structural check and
# would be published on the estate board as that project's next action.
_PLACEHOLDER_RES = (
    re.compile(r"^_.*_$"),                        # _Task 1_, _Description_
    re.compile(r"^(task|item|step|todo)\s*\d*$", re.IGNORECASE),
    re.compile(r"^(tbd|todo|fixme|xxx)\b", re.IGNORECASE),
    re.compile(r"^\W*$"),                         # punctuation/emphasis only
    re.compile(r"\b(add|fill in|describe|replace)\s+(the\s+)?"
               r"(first\s+)?(task|item|description|this)\b", re.IGNORECASE),
)


def is_placeholder(text: str) -> bool:
    """True when a task line is template scaffolding rather than work.

    Deliberately conservative: it must be *clearly* a placeholder. A false
    positive here silently hides a real next action, which is worse than
    occasionally publishing a vague one.
    """
    stripped = text.strip().strip("*").strip()
    if not stripped:
        return True
    return any(rx.search(stripped) for rx in _PLACEHOLDER_RES)


def first_unchecked_task(text: str) -> str | None:
    """First *real* ``- [ ]`` item, prefixed with the section it sits under.

    "First unchecked box" on its own is a weak signal in a long roadmap:
    the first hit is often a known-issues note under a session that is
    otherwise finished, and a bare line out of context reads as nonsense.
    Carrying the heading makes an imperfect guess legible, which beats
    guessing harder and still being wrong silently.

    Template placeholders are skipped rather than returned.  If every
    unchecked item is scaffolding, this returns ``None`` so the caller
    falls through to git — "here is the last thing you actually did" is
    more use than "_Task 1_".
    """
    for heading, body in _sections(text):
        for line in body:
            m = _UNCHECKED_RE.match(line)
            if not m:
                continue
            item = m.group(1).strip()
            if is_placeholder(item):
                continue
            # A real item under a placeholder heading ("Session 1:
            # _Description_") keeps the item and drops the heading.
            if heading and not is_placeholder(heading.split(":", 1)[-1]):
                return f"{heading} → {item}"
            return item
    return None


def count_unchecked(text: str) -> int:
    """How many ``- [ ]`` items remain across the document."""
    return sum(1 for line in text.splitlines() if _UNCHECKED_RE.match(line))


def count_checked(text: str) -> int:
    """How many ``- [x]`` items the document records as done."""
    return sum(1 for line in text.splitlines() if _CHECKED_RE.match(line))


def count_open_snags(text: str) -> int:
    """Snags under the "open" heading only.

    Fixed snags are kept in this repo as a markdown table for the record,
    so a document-wide count of ``SNAG-`` would report every bug ever
    fixed as outstanding.
    """
    total = 0
    for heading, body in _sections(text):
        h = heading.lower()
        if "open" not in h and "outstanding" not in h:
            continue
        total += sum(1 for line in body if _SNAG_LINE_RE.match(line))
    return total


def next_action_from_handoff(text: str) -> str | None:
    """The next action a handoff names, by three widening attempts.

    Ordered by how deliberately the author signalled it: an explicit
    "next" heading, then an unchecked box anywhere, then nothing.  Prose
    under a non-"next" heading is *not* guessed at — a handoff's opening
    paragraph is usually what was just finished, and reporting that as the
    next action would be confidently wrong.
    """
    for heading, body in _sections(text):
        if "next" in heading.lower():
            found = _first_meaningful(body)
            if found:
                return found

    unchecked = first_unchecked_task(text)
    if unchecked:
        return unchecked

    return None


def handoff_date(text: str, fallback: date | None = None) -> date | None:
    """The date the handoff claims, read from its first heading.

    Authored date beats file mtime: a fresh clone or a checkout rewrites
    every mtime on disk, which would make five-month-old handoffs across
    the estate look like they were all written this morning.
    """
    for line in text.splitlines():
        m = _HEADING_RE.match(line)
        if not m:
            continue
        d = _ISO_DATE_RE.search(m.group(2))
        if d:
            try:
                return date(int(d.group(1)), int(d.group(2)), int(d.group(3)))
            except ValueError:
                return fallback
        break
    return fallback


def scan_roadmap(project_path: Path, now: datetime | None = None) -> dict[str, Any]:
    """Collect the roadmap facts for one project.

    Returns a findings-shaped dict.  ``next_action`` is ``None`` when
    neither a handoff nor a task list supplies one — the caller is
    expected to fall back to git, which this module deliberately cannot
    see (keeping it pure and trivially testable).
    """
    now = now or datetime.now(UTC)
    today = now.date()

    handoff_text, handoff_rel, handoff_others = _read_handoff(project_path)
    tasks_text, tasks_rel = _read(project_path, TASKS_PATHS)
    snags_text, _ = _read(project_path, SNAGS_PATHS)
    ideas_text, _ = _read(project_path, IDEAS_PATHS)
    status_text, _ = _read(project_path, STATUS_PATHS)

    info: dict[str, Any] = {
        "has_handoff": handoff_text is not None,
        "has_tasks": tasks_text is not None,
        "has_snags": snags_text is not None,
        "has_ideas": ideas_text is not None,
        "has_status": status_text is not None,
        "next_action": None,
        "next_action_source": None,
        "handoff_age_days": None,
        # Which of the four shapes was read, and which were passed over.
        # Reported rather than merely resolved: two handoffs in one repo is
        # a migration left half-done, and it is invisible to whoever wrote
        # the one that lost.
        "handoff_path": handoff_rel or None,
        "handoff_duplicates": handoff_others,
        # None means "not measurable" (no task list, or one that does not
        # use checkboxes); 0 means "measured, nothing outstanding".
        "open_tasks": None,
        "done_tasks": None,
        "open_snags": 0,
    }

    if handoff_text is not None:
        mtime_date = None
        try:
            stat = (project_path / handoff_rel).stat()
            mtime_date = datetime.fromtimestamp(stat.st_mtime, tz=UTC).date()
        except OSError:
            pass
        written = handoff_date(handoff_text, fallback=mtime_date)
        if written:
            info["handoff_age_days"] = max(0, (today - written).days)
        action = next_action_from_handoff(handoff_text)
        if action:
            info["next_action"] = action
            info["next_action_source"] = "handoff"

    if tasks_text is not None:
        open_count = count_unchecked(tasks_text)
        done_count = count_checked(tasks_text)
        # Not every roadmap uses checkboxes. Alfred tracks sessions in a
        # markdown table with a Status column, so counting boxes there
        # yields 0 — and "0 open tasks" for the busiest project on the box
        # is a confident lie. Absent counts say "not measurable here",
        # which is the truth. (Same distinction the disk review already
        # draws between "unchanged" and "unknown".)
        if open_count or done_count:
            info["open_tasks"] = open_count
            info["done_tasks"] = done_count
        else:
            info["open_tasks"] = None
            info["done_tasks"] = None
        if info["next_action"] is None:
            action = first_unchecked_task(tasks_text)
            if action:
                info["next_action"] = f"{action}  (from {tasks_rel})"
                info["next_action_source"] = "tasks"

    if snags_text is not None:
        info["open_snags"] = count_open_snags(snags_text)

    missing = [
        name
        for name, present in (
            ("handoff", info["has_handoff"]),
            ("tasks", info["has_tasks"]),
            ("status", info["has_status"]),
        )
        if not present
    ]
    info["missing_docs"] = missing

    return info
